[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sae-bench"
version = "0.1.0"
description = "Research pipeline for SAE similarity experiments"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["sae_bench"]
